### ISSUE TITLE
misplaced superscript in align environment

### ISSUE THREAD

**Issue by Debenben** [mathjax/mathjax-v3#120]
Using the current demo https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html with Firefox/Linux and input `\begin{align} \sum_a^b \end{align}` the b gets shifted by the align environment:

![screenshot from 2018-05-18 22-10-29](https://user-images.githubusercontent.com/35615783/40255719-6d2fae32-5ae8-11e8-8032-08d6a4facbba.png)

**Comment by dpvc** [comment]
Thanks for the report.  This is due to the CSS for the align environment bleeding through to the upper limit.  It will be fixed in the next release, but you can add 

```
mix-over {
text-align: left
}
```

to correct it for now.

**Comment by dpvc** [comment]
This has been merged into the master branch.
