### ISSUE TITLE
spacing of \colon

### ISSUE THREAD

**Issue by Debenben** [mathjax/mathjax-v3#121]
Using the current demo https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html with Firefox/Linux and input `\begin{align}x \colon y \to z \\ x : y\to z \end{align}` results in:

![screenshot from 2018-05-18 22-29-51](https://user-images.githubusercontent.com/35615783/40256509-0447828e-5aeb-11e8-8dfa-ad298912d2e8.png)

where in the first line the colon should be closer to the x than to the y like in LaTeX:

![screenshot from 2018-05-18 22-30-45](https://user-images.githubusercontent.com/35615783/40256549-23cf5000-5aeb-11e8-997e-134b30f812d6.png) 

or MathJax on math.stackexchange: 

![screenshot from 2018-05-18 22-32-49](https://user-images.githubusercontent.com/35615783/40256643-6d170082-5aeb-11e8-9b25-a8a0e77e2b71.png)

see https://tex.stackexchange.com/questions/37789 for further discussion of the difference.

**Comment by dpvc** [comment]
Thanks for the bug report.

@Volker, the `\colon` macro is supposed to set the tex class to `PUNCT`, but it does seem to be.  Can you check into this?

**Comment by zorkow** [comment]
Corrected to @zorkow. I'll have a look.

**Comment by dpvc** [comment]
@zorkow, any word on this issue? It seems to still be in beta.3, and we will need to get it fixed for the production release.
