### ISSUE TITLE
ETA on a production ready release?

### ISSUE THREAD

**Issue by jfstephe** [mathjax/mathjax-v3#124]
Hi,
This is probably not the best format for this question, but do you have an ETA on this being stable/ready for production use?
The only information I could find was on [this old stackoverflow post](https://stackoverflow.com/questions/40989264/integrate-mathjax-into-systemjs-build?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), but I reserve the right to have been looking in the wrong place :-).
Thanks,
John

**Comment by dpvc** [comment]
We have recently released [3.0.0-alpha.6](https://github.com/mathjax/mathjax-v3/releases), which delivers TeX and MathML input together with CommonHTML output.  We are planning a public beta release next month.  We don't have a date for a production release, but I would hope by the end of the summer.  You can follow the [developer forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-dev) for more information, and the [mathjax-v3](https://github.com/mathjax/mathjax-v3) github site for the actual code.

**Comment by jfstephe** [comment]
Awesome. Many thanks! :-)
