### ISSUE TITLE
placement of integral limits

### ISSUE THREAD

**Issue by Debenben** [mathjax/mathjax-v3#128]
Using the current demo https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html with Firefox/Linux and input `\int_a^b f(x) dx` the limits seem to be too far away from the integral: 
![screenshot from 2018-06-11 22-50-19](https://user-images.githubusercontent.com/35615783/41256467-f52baeb4-6dc9-11e8-89f8-fa5445aba3fb.png)
With an additional align environment `\begin{align}\int_a^b f(x) dx\end{align}` the b moves closer to the integral:
![screenshot from 2018-06-11 22-51-02](https://user-images.githubusercontent.com/35615783/41256513-1d7f02a8-6dca-11e8-8dfb-5c60c7ff8b58.png)

**Comment by dpvc** [comment]
Thanks for the report.  I see the same thing, and will look into it.

**Comment by dpvc** [comment]
I've made pull requests for the two problems that are listed here (the extra space after the integral, and the improper alignment within `\begin{align}...\end{align}`.
