### ISSUE TITLE
[TeX input] tracking missing extensions

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#133]
I'm not sure where to track this so feel free to move and close this. I picked these up while testing the math.SE tutorial.

* verb
* cancel 
* enclose 
* AMScd
* extpfeil
* `\require`

**Comment by dpvc** [comment]
These are all in beta.3 except for `\require`.  Now that I have a mechanism for breaking MathJax3 into separate components, a `\require` macro could be implemented.

**Comment by dpvc** [comment]
`\require` is in beta.4 (along with all the others), so I'm closing this issue.
