### ISSUE TITLE
mathbackground does not cover the expression's background

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#137]
For example 

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle mathbackground="red">
      <mn>1</mn>
  </mstyle>
</math>
```

Renders as 

![image](https://user-images.githubusercontent.com/426686/43723868-fd30fe8e-9998-11e8-9085-f844e2318077.png)

in mj3-demos, i.e., the background color is not filling the content's background, only a thin part at the bottom.

When I add

```css
mjx-math * {
    background: inherit;
}
```

it looks ok but I'm not sure if that has side effects.

**Comment by dpvc** [comment]
It looks like the CSS

```
mjx-mstyle {
  display: inline-block;
}

is missing.  I thought these were added automatically for all the node types, but there I will check the code to see what is happening.
