### ISSUE TITLE
mfenced.ts toCHTML() contains debug code

### ISSUE THREAD

**Issue by stnor** [mathjax/mathjax-v3#141]
Hi!
Please remove the call to 'this.drawBBox();'
I get really colorful output in beta1 due to this :(

Any plans for pushing a new beta anytime soon?

**Comment by dpvc** [comment]
Yes, I found that myself just last week (ironically) as I was working on the SVG version of mfenced.  The `drawBBox()` call will be removed on the next beta.

> Any plans for pushing a new beta anytime soon?

Yes.  I am nearing completion of the SVG output, and should have a new beta that includes that soon.  Perhaps as early as next week.
