### ISSUE TITLE
AsyncLoad warnings in console (Webpack 4)

### ISSUE THREAD

**Issue by stnor** [mathjax/mathjax-v3#142]
I am getting a few warnings from AsyncLoad.js. Are you planning to fix these?

````
client:148 ./node_modules/mathjax3/mathjax3/util/AsyncLoad.js 8:15-34
Critical dependency: the request of a dependency is an expression

client:148 ./node_modules/mathjax3/mathjax3/util/AsyncLoad.js 8:15-34
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
````

**Comment by dpvc** [comment]
This is a duplicate of (part of) #88.  [This comment](https://github.com/mathjax/mathjax-v3/issues/88#issuecomment-378257424) tells you how to work around the warning.

**Comment by stnor** [comment]
I tried using the webpack (4.16.5) workaround with beta1 as described in #88 .

````javascript
      new webpack.NormalModuleReplacementPlugin( // remove MathJax3 warnings
          /AsyncLoad\.js/,
          function (resource) {
            resource.request = resource.request.replace(/AsyncLoad/,"AsyncLoad-disabled");
          }
      )
````
However, I'm getting:

````
client:162 ./node_modules/mathjax3/mathjax3/input/mathml/MmlEntities.js
Module not found: Error: Can't resolve '../../util/AsyncLoad-disabled.js' in '/Users/stnor/devel/src/nomp/frontend/node_modules/mathjax3/mathjax3/input/mathml'
errors @ client:162
````

Also I'm thinking the regexp should be more specific to mathjax rather than everything matching    /AsyncLoad\.js/,

Any ideas?

**Comment by stnor** [comment]
There doesn't seem to be any JS version of "AsyncLoad-disabled.ts" in the beta.

**Comment by stnor** [comment]
I'd rather wait for a new beta rather than creating a class for my app that would do the same as the (not) provided workaround.

**Comment by dpvc** [comment]
> Also I'm thinking the regexp should be more specific to mathjax rather than everything matching /AsyncLoad.js/,

Sure, use whatever is necessary in your situation.

> There doesn't seem to be any TS or JS version of "AsyncLoad-disabled.ts" in the beta.

I've just checked the GitHub beta branch and ts file is there (See [here](https://github.com/mathjax/mathjax-v3/blob/beta/mathjax3-ts/util/AsyncLoad-disabled.ts), and I just downloaded the the npm packaged version, and both the files are there.   (The .js files aren't stored on github, but are included in the npm package.)

Are you sure you are using the beta branch (if from GitHub), or the current version (if from npm)?

> I'd rather wait for a new beta rather than creating a class for my app that would do the same as the (not) provided workaround.

I'm not sure I understand.  The `AsynchLoad.js` file is not expected to change in the next beta, so waiting for beta.2 will not change this.

**Comment by stnor** [comment]
1. I have a massive JS app, and the best way i can limit the regexp is by using something like:
/\.\.\/util\/AsyncLoad\.js/ and that seems like too much of a risk to hit other libraries or my own code.
Would it be possible to make it include mathjax3 even thought the imports are ..\util\... in mathjax?

2. Doh, I switched branch (master was using alpha1) and forgot to yarn install... sorry

**Comment by dpvc** [comment]
> Would it be possible to make it include mathjax3 even though the imports are ..\util... in mathjax?

I'm not sure what "it" refers to in "make it include..."  If you mean webpack, I'm afraid I am only a novice webpack user, and don't know if it is possible to force path expansion before the regex.  Did you try `/mathjax3\/util\/AsyncLoad\.js/` to see if it could be found that way?  

If you mean MathJax itself, then I suppose it could be done by changing 

    import {asyncLoad} from '../../util/AsyncLoad.js';

to 

    import {asyncLoad} from '../../../mathjax3/util/AsyncLoad.js';

It looks like the only reference to AsyncLoad uses two sets of double dots, so you might be able to reduce the chance of incorrect matches by using

    /\.\.\/\.\.\/util\/AsynchLoad\.js/

if that helps.

**Comment by stnor** [comment]
This is a safe approach should anyone else want to remove the warnings:

````javascript
      new webpack.NormalModuleReplacementPlugin( // remove MathJax3 warnings
          /AsyncLoad\.js/,
          function (resource) {
            if (resource.context.endsWith('mathjax3/util')) {
              resource.request = resource.request.replace(/AsyncLoad/,'AsyncLoad-disabled');
            }
          }
      )
````

**Comment by dpvc** [comment]
Thanks for finding the solution!
