### ISSUE TITLE
Feature request/question: Parse just one element

### ISSUE THREAD

**Issue by stnor** [mathjax/mathjax-v3#143]
I can't figure out how to get MathJax3 to parse (only) the current element from my angularjs directive.

I've tried to pass an element (instead of the document) to MathJax.document(), but that doesn't seem to work.
How is one supposed to work with MathJax in a component-based architecture?

````javascript
      const html = MathJax.document(window.document, {
        InputJax: mathML,
        OutputJax: new CHTML({font: font})
      });

      html.findMath()
          .compile()
          .typeset()
          .updateDocument();
    });
````

**Comment by stnor** [comment]
I may have found something here:
````
      html.findMath({elements: [element[0]]})
````

is that is?

**Comment by stnor** [comment]
Personally I would make the element(s) a mandatory parameter to findMath()

**Comment by dpvc** [comment]
> is that it?

Yes, that would restrict to just the element that you are interested in.

You may also want to look at the [v3 demos](https://github.com/mathjax/mj3-demos), and in particular, [this one](https://github.com/mathjax/mj3-demos/blob/master/mj3-tex2html-global.js), which implements a `Typeset()` command that takes a TeX string and returns a DOM tree for the typeset math.  You can then insert that DOM tree into your component.

**Comment by stnor** [comment]
Thanks.
