### ISSUE TITLE
Adaptor is not a function

### ISSUE THREAD

**Issue by jandraor** [mathjax/mathjax-v3#145]
Hello,

I'm trying MathJax on my website, but with the following code I get an 'adaptor is not a function' error. 

```
// the MathJax core
const MathJax = require("../../../../node_modules/mathjax3/mathjax3/mathjax.js").MathJax;

// Tex input
const TeX = require("../../../../node_modules/mathjax3/mathjax3/input/tex.js").TeX;
// HTML output
const CHTML = require("../../../../node_modules/mathjax3/mathjax3/output/chtml.js").CHTML;
// Use browser DOM
const adaptor = require("../../../../node_modules/mathjax3/mathjax3/adaptors/browserAdaptor").browserAdaptor();
// Register the HTML document handler
require("../../../../node_modules/mathjax3/mathjax3/handlers/html.js").RegisterHTMLHandler(adaptor());
```

I tried to change the route to:

```
const adaptor = require("../../../../node_modules/mathjax3/mathjax3/adaptors/browserAdaptor.js").browserAdaptor();
```

But it wouldn't work.

**Comment by dpvc** [comment]
In the line

```
const adaptor = require("../../../../node_modules/mathjax3/mathjax3/adaptors/browserAdaptor").browserAdaptor();
```

you have already called the ` browserAdaptor()` function to create the adapter, so `adaptor` is already the adaptor you need, not the function to create one.  So you only need to do

```
require("../../../../node_modules/mathjax3/mathjax3/handlers/html.js").RegisterHTMLHandler(adaptor);
```

(without the parentheses after `adaptor`) to pass the adapter to the handler.

If you took this code from an example documented somewhere, can you let us know where?  It may need to be corrected.

**Comment by jandraor** [comment]
Hi,

It compiled! Now I can try it. 

Actually, I got that code from one of your [demos](https://github.com/mathjax/mathjax-v3/wiki/A-first-usable-demo-(using-webpack)).

**Comment by dpvc** [comment]
Thanks for the reference to the example.  I have fixed it.

Glad it is compiling for you now.
