### ISSUE TITLE
TeX \require{cancel} not work

### ISSUE THREAD

**Issue by h0tc0d3** [mathjax/mathjax-v3#149]
![mathjax](https://user-images.githubusercontent.com/10059293/46407918-2691cf80-c719-11e8-8a27-9b54c01aabd7.png)
Sample
```
$$P(A + B) = \frac{\require{cancel}\cancelto{1}{3}}{\cancel{5}} *
                \frac{\cancel{5}}{\cancelto{3}{9}} = \frac{1}{3}$$
```

**Comment by dpvc** [comment]
The `\require` macro is not part of v3, as loading extensions is handled differently in v3.  The cancel extension has only recently been implemented, and is part of the recently released beta.2 version.  Try it in the [interactive demo](https://mathjax.github.io/mj3-demos/tex2html/mj3-tex2html-global.html) without the `\require{cancel}` to see.
