### ISSUE TITLE
Not working `\hbar`

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/mathjax-v3#178]
Not working `\hbar`
`\hbar` returns an error `Uncaught TypeError: Cannot read property 'chars' of undefined`

**Comment by OlgaRedozubova** [comment]
Maybe it's needed to change the file `/mathjax3-ts/input/tex/base/BaseMappings.ts`
`-  hbar:         ['\u210F', {variantForm: true}],`

`+  hbar:         ['\u210F', {mathvariant: TexConstant.Variant.NORMAL,
                            variantForm: true}],`

**Comment by dpvc** [comment]
I have confirmed your report, and suspect that your solution is correct, but I haven't tried it yet.  We will check into it and include a fix in the next release.
