### ISSUE TITLE
\hline and \hdashline not properly working for tex2svg

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/mathjax-v3#183]
```
\begin{array}{r}{73} \\ {-\quad 36} \\ \hline 37\end{array}
```

![screenshot-mathjax github io-2019 01 14-13-41-21](https://user-images.githubusercontent.com/32493105/51111481-d7be0080-1804-11e9-9303-4807238c2e95.png)

```
\begin{array}{r}{73} \\ {-\quad 36} \\ \hdashline 37\end{array}
```

![screenshot-mathjax github io-2019 01 14-13-50-55](https://user-images.githubusercontent.com/32493105/51111489-de4c7800-1804-11e9-930d-206df90f86b3.png)

**Comment by OlgaRedozubova** [comment]
Maybe it's needed to change the file `../mathjax3-ts/output/svg/Wrappers/mtable.ts`
...
`if (lines[i] !== 'none') {
                this.adaptor.append(svg, this.makeHLine(y, lines[i], rLines[i]));
            }`

**Comment by dpvc** [comment]
Thanks for the report.  You are correct about the location of the error.  It will be fixed in the next release.
