### ISSUE TITLE
[SVG] \tag leads to blank rendering

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#185]
E.g., `\begin{equation} 1 = 0. \tag{1} \end{equation}` renders as blank on everything but Firefox for me.

The W3C validator flags the resulting SVG markup as invalid due to the transforms on the nested SVG.

**Comment by pkra** [comment]
The "stretchy" trick is really neat by the way.

**Comment by dpvc** [comment]
OK, thanks for the report.  I've been doing testing mostly in Firefox, so that is why I didn't catch this.

I've checked into it, and it looks like I can wrap the nested `<svg>` elements in `<g>` elements with the transforms to get the same effect.

**Comment by dpvc** [comment]
> The "stretchy" trick is really neat by the way.

I was pleased to be able to find a way to make that work.  The fixed width of the svg required for labels in v2 was always problematic.

**Comment by pkra** [comment]
Awesome. Thanks, Davide.
