### ISSUE TITLE
NodeFactory setMmlFactory?

### ISSUE THREAD

**Issue by hubgit** [mathjax/mathjax-v3#191]
There's [a commit in the beta.3 branch](https://github.com/mathjax/mathjax-v3/commit/736b5cf5ca8e1b47ba05aaae69b0c9f8286b1a7d#diff-7573c2f77efb61659c53d99e27dfa698L52) that isn't in the master branch, which appears to make it necessary for something to call the tex NodeFactory's `setMmlFactory` method.

How should this be called in order to avoid the `Cannot read property 'create' of null` error that's otherwise thrown when the NodeFactory tries to use its `mmlFactory`?

I'm using mathjax-v3 in a browser via webpack; this is something that changed between beta.2 and beta.3, as I wasn't seeing the error before.

**Comment by dpvc** [comment]
Yes, there is a change in this respect between beta.2 and beta.3.

Can you give a code snippet of what you are doing, so I can suggest how to update it?  It is hard to tell without more details.

**Comment by hubgit** [comment]
I've actually just solved it, because I found [this line](https://github.com/mathjax/mathjax-v3/pull/182/files#diff-2a543084d251e82e9b480235aa5b2747R31) in a recent pull request that looked related.

```js
const OutputJax = new SVG()
const doc = new GenericMathDocument(document, browserAdaptor(), { OutputJax })

const InputJax = new TeX({})
InputJax.setMmlFactory(doc.mmlFactory) // added this line
```

**Comment by hubgit** [comment]
Even simpler, passing the `InputJax` option to the doc constructor works too.

```js
const InputJax = new TeX({})
const OutputJax = new SVG()
const doc = new GenericMathDocument(document, browserAdaptor(), {
  InputJax,
  OutputJax,
})
```

**Comment by dpvc** [comment]
Yes, I was going to point out that it is the document that sets the node factory for the input and output jax, so I wanted to see how you were creating your documents.  Glad you worked it out.
