### ISSUE TITLE
directory structure

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#21]
Move the webworker code into another repository and move the v3 folder contents to the top level.

**Comment by pkra** [comment]
Ping.

**Comment by dpvc** [comment]
Doing this while the ts-core PR is open would cause difficulties with the merge, and complicate the development processes while waiting for that PR to be reviewed.  We need to wait until there are no outstanding major PRs to do this.

**Comment by pkra** [comment]
There are no PRs open. Can we please fix this?
