### ISSUE TITLE
[CHTML output] stretchy bar vanishes

### ISSUE THREAD

**Issue by zorkow** [mathjax/mathjax-v3#239]
Stretchy bar vanishes in CHTML output when it needs extenders. For example, here
```LaTeX
\left<\frac{a}{b}\middle|b\right>
```
it vanishes, whereas here
```LaTeX
\left<a\middle|b\right>
```
it does not.

(Looks fine in SVG output.)

**Comment by dpvc** [comment]
This was taken care of in #236 (originally for horizontal stretchy characters, but I added the fix for vertical stretchy bars the other day).
