### ISSUE TITLE
`thickness` attribute has no effect on enclosed elements 

### ISSUE THREAD

**Issue by zorkow** [mathjax/mathjax-v3#260]
Examples:
```LaTeX
\enclose{horizontalstrike}{x}
\enclose{horizontalstrike}[thickness=5]{x}
\enclose{circle}{x}
\enclose{circle}[thickness=100]{x}
```
The `thickness` of the enclosing elements stays the same. 
It appears that the `menclose` node expect these values as `data` attributes. 
Currently they are set as regular attributes, i.e., `thickness, padding`, etc. Do you want me to set them differently?

**Comment by dpvc** [comment]
thickness and padding are not official attributes of `menclose`.  I added those to allow more flexibility in the output in v1 long ago, which was before there were `data-*` attributes.  For v3, it makes sense to move these to "legal" attributes (using `data-`) instead. The output jax look for `data-thickness` and `data-padding`, so yes, it would be good to change `\enclose` to work that was as well.

**Comment by zorkow** [comment]
I've implemented that for `thickness`, `padding`, and `arrowhead`.
