### ISSUE TITLE
Multiple rendering state information on a single page

### ISSUE THREAD

**Issue by jasongrout** [mathjax/mathjax-v3#34]
In JupyterLab we have multiple continuous documents on the same page (for example, two Jupyter notebooks side by side on a page). Is it (or will it be) possible to have two different states for the mathjax renderer on the same page? For example, equation numbering should be continuous in each Jupyter notebook.

CC @ian-r-rose @mpacer

**Comment by dpvc** [comment]
Yes.  There is no global state (as there is in v2); the various components can be instantiated separately, and each instance has its own state.  You can process multiple separate documents, each with its own configuration, and documents don't have to have a browser presence.  So I think this will be much more flexible than the current arrangement.

In your case, each notebook could be a separate document with its own instance of the MathJax components, and you could handle each independently.

**Comment by jasongrout** [comment]
Great, thanks!  That's what I was thinking/hoping, just wanted to confirm from conversations we were having today about mathjax in the Jupyter notebook.
