### ISSUE TITLE
webpack issues with TeX input

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#63]
A quick documentation of what I've tried.

## branches

I merged the `moving_parse_methods1 branch into the `stretchy-cells` branch and tried to build an analogous example to https://github.com/mathjax/mathjax-v3/wiki/A-first-usable-demo-(using-webpack).

## setup example

* texpage.js

```javascript
//
// the MathJax core
import  {MathJax} from "./mathjax3/mathjax.js";
// TeX input
import {TeX} from './mathjax3/input/tex.js';

// HTML output
import {CHTML} from "./mathjax3/output/chtml.js";

// handler for HTML documents
import {HTMLHandler} from "./mathjax3/handlers/html/HTMLHandler.js";
MathJax.handlers.register(new HTMLHandler());

// initialize mathjax with with a DOM document (e.g., browser, jsdom); other documents are possible
const html = MathJax.document(document, {
    InputJax: new TeX(),
    OutputJax: new CHTML()
});

window.addEventListener("load", function () {
    console.time('wrapper');
    // process the document
    html.findMath()
        .compile()
        .getMetrics()
        .typeset()
        .updateDocument();
    console.timeEnd('wrapper');
});
```

* webpack.config

```javascript
const Uglify = require("uglifyjs-webpack-plugin");
module.exports = {
    entry: './texpage.js',
    output: {
        path: __dirname,
        filename: 'webpack.dist.js'
    },
    plugins: [
        new Uglify()
    ]
};
```

## first problem: relative paths

The first problem came from the paths in the "legacy" code (which according to @zorkow is due to systemjs being weird about them).

So I manually changed anything like `require('mathjax3/...')` (or similar import statements) to add sufficient `../` prefixes.

**QUESTION** can we switch over to correct relative paths for the TeX "legacy" code?

I ran the tests after changing the paths and they didn't throw errors but had test failures; thus I'm not sure if there's a problem with using relative paths.

## second problem

Once these were changes, webpack could resolve the resources but then ran into an actual problem in the code

```bash

ERROR in ./mathjax2/legacy/jax/input/TeX/StackItem.js
Module parse failed: ./mathjax2/legacy/jax/input/TeX/StackItem.js Duplicate constructor in the same class (817:2)
You may need an appropriate loader to handle this file type.
|   }
|
|   constructor(name, numbered, taggable, stack) {
|     super();
|     this.type = 'AMSarray';
 @ ./mathjax2/legacy/extensions/TeX/AMSmath.js 31:12-55
 @ ./mathjax2/input/TeX.js
 @ ./mathjax3/input/tex.js
 @ ./texpage.js
```

According to @zorkow this is a bug in the current TeX parser code.

**Comment by zorkow** [comment]
I thought I had fixed the second problem last night already in said branch. @pkra could you try again if that still persists?

**Comment by pkra** [comment]
> in said branch

I seem to have an up-to-date `moving_parse_methods` branch and its last change is 22h ago. Have you pushed to GitHub?

**Comment by pkra** [comment]
Update. The bug has fixed the compilation problem.

The question remains what to do with those absolute paths.

**Comment by pkra** [comment]
I've also commented out all the `console.log`s which had a significant impact on performance.

**Comment by pkra** [comment]
> I've also commented out all the console.logs which had a significant impact on performance.

Correction. It only had a serious perf impact when the dev tools are open.

**Comment by pkra** [comment]
I've pushed a build and sample page to the demo branch (and updated the mm2html build).

Live at https://rawgit.com/mathjax/mathjax-v3/demo/demo/.

The TeX input seems to have some minor problems matching stretchy parens but otherwise the build seems ok.

**Comment by dpvc** [comment]
Part of the problem with the parens is the `\mathchoice` issues (which is used in the probability formula).  But there are other problems as well the I will have to look into.

When I run the demo page in Safari, I get an error message about using `let t` twice, but I don't see where that is occurring.

**Comment by pkra** [comment]
> When I run the demo page in Safari, I get an error message about using let t twice, but I don't see where that is occurring.

Interesting. Gnome's WebKitGTK+ 2.18.0 browser is working fine.

There are also JS errors (expected semicolon) on IE11; I didn't test lower than that.

**Comment by pkra** [comment]
This issue has been resolved in the newest TeX parser branch.

**Comment by pkra** [comment]
(by which I mean the two original problems with the paths and stackitem)
