### ISSUE TITLE
missing document

### ISSUE THREAD

**Issue by jasongrout** [mathjax/mathjax-v3#68]
I tried using the alpha.1 npm package to implement a new typesetter for JupyterLab:

https://github.com/jasongrout/jupyter-renderers/blob/mathjax3/packages/mathjax3-extension/src/index.ts

It seems that in the updateDocument call at https://github.com/jasongrout/jupyter-renderers/blob/3aa8e2b3ec9543eae8f831d7bc42532c279e228b/packages/mathjax3-extension/src/index.ts#L50, it calls down into HTML.node, where that function tries to use `this.document`, but `this.document` is null:

<img width="1146" alt="screen shot 2017-11-17 at 6 07 35 pm" src="https://user-images.githubusercontent.com/192614/32975972-8aa54b08-cbc2-11e7-9008-03b785842c66.png">

Does my code look right?

**Comment by jasongrout** [comment]
(This is trying to typeset `$x^2$`)

**Comment by ian-r-rose** [comment]
One of the examples seems to get around this by manually setting `chtml.nodes`: https://github.com/mathjax/mj3-demos/blob/master/mj3-mml2html-global.js#L10

**Comment by jasongrout** [comment]
Ah. I was basing my code on https://github.com/mathjax/mj3-demos/blob/2d1b3454761d3df9987aacd7722aeb5bd13b6d5b/mj3-tex2html.js

**Comment by dpvc** [comment]
You shouldn't need to set the document yourself.  It should be set automatically.  I'll check into it.

**Comment by jasongrout** [comment]
With our current version of the code, we don't seem to get this error anymore, so I'm willing to chalk it up to not knowing how to use mathjax correctly.
