### ISSUE TITLE
Forcing a re-typeset of an HTML document

### ISSUE THREAD

**Issue by ian-r-rose** [mathjax/mathjax-v3#69]
In the same effort as #68:

We would like to re-render portions of the document many times. I was running into a problem where more than one call to a MathJax document become a no-op, apparently because the fields `processed.findMath`, `processed.compile`, etc had been set to true.

Is it not intended that a document get rendered more than once? I was able to force a re-render by manually setting those fields to be true, but it doesn't feel like this is necessarily recommended.

**Comment by jasongrout** [comment]
To be fair, we'd like to replace a portion of the document with text, and rerender math in that specific node. I don't think we plan to rerender something that has already been rendered.

**Comment by pkra** [comment]
Excellent point. Creating a new  MathJax.document (re-using window.document) is one way.

@dpvc @zorkow what's the preferred way to re-render/update a document?

**Comment by pkra** [comment]
Oh. Sorry for cross posting @jasongrout.

If you are looking to render just one expression, then you don't need a MathJax.document, se https://github.com/mathjax/mj3-demos/blob/master/mj3-tex2html-global.js.js#L14-L19 for an example.

**Comment by pkra** [comment]
And now I see you already found that in #68. I really shouldn't write things before the first coffee...

**Comment by dpvc** [comment]
> I see you were talking about a `MathJax.document`. Good question - @dpvc, is it expected that a new `MathJax.document` is created for every div we want to render?

No, the `processed` flags that you are resetting are part of the mechanism for handling asynchronous processing (which was necessary for the legacy v2 code up until the new TeX input processor was made available a few weeks ago).

If you want to process a document a second time, use the `.reset()` or `.clear()` methods of the math document.  Use `.reset()` if you want to reset the flags but keep the math items that have already been found (i.e., you want to re-compile and re-typeset them); use `.clear()` if you want to discard the stored math items as well.  If you are chancing the content of the document to remove the old math and replace it with new math, you want `.clear()`.  E.g., 

```
    html.findMath({elements: [node]})
    .clear()
    .compile()
    .getMetrics()
    .typeset()
    .updateDocument();
```

Your earlier version with the document being created once in the constructor was the right approach.  You just need to add the `.clear()` call.  The current version of constructing a new document, and input and output processors is less efficient.  (Even if you wanted to create a new document each time, you could reuse the same CHTML and TeX object, as long as they are only used in one document at a time.)

**Comment by jasongrout** [comment]
It seems I need to put the `.clear()` before the `.findMath`, but it works!

**Comment by jasongrout** [comment]
(Well, it works except that it can't load the mathjax2 fonts, because JupyterLab doesn't allow us to give extra redirects in the webpack config to tell it where to find the fonts - but the hardcoded fonts is a separate issue.)

**Comment by ian-r-rose** [comment]
Great, `clear()` is what we were looking for, thanks!
