### ISSUE TITLE
(js)dom dependency

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#72]
v3 currently relies on jsdom when running in nodeJS.

The example in

* https://github.com/mathjax/mathjax-v3/blob/master/samples/replace-html.js 
* https://github.com/mathjax/mathjax-v3/blob/master/samples/lib/myHTMLNodes.js 
* https://github.com/mathjax/mathjax-v3/blob/master/samples/lib/myDOM.js 

implements a minimal replacement.

I'm wondering if that approach should not be the default.

**Comment by pkra** [comment]
Ahead of the next TC, I wanted to add that the example is already close to [HAST](https://github.com/syntax-tree/hast) so generating that seems easy  and opens up a rich ecosystem, including most vDom approaches. Alternatively, something that already has tools converting to HAST might be an option (e.g parse5's AST).

**Comment by dpvc** [comment]
Note the jsdom has been removed as a dependency in the alpha.6 release (though you can install it yourself and still use the `jsdomAdaptor` if you wish).
