### ISSUE TITLE
IE11 needs Elements.classList polyfill

### ISSUE THREAD

**Issue by stnor** [mathjax/mathjax-v3#87]
Hi,
MathMLCompile.makeNode uses Elements.classList. which is not supported in IE11 and lower.
Is this by accident or design?

Also, It would be good if errors like this are logged and not only displayed as "Math Input Error".
It's easier to debug if you have a stack trace.

**Comment by pkra** [comment]
Duplicate of https://github.com/mathjax/mathjax-v3/issues/62

**Comment by stnor** [comment]
Sorry for the dup.
Weird thing is that even when using the polyfill classList.js: 1.2.20171210
I still get undefined in IE11 in MathMlCompile.makeNode...

````
console.log('node:', node, 'node.classList:', node.classList)
````
logs: 
````
node: [object Element] node.classlist: undefined
````

**Comment by stnor** [comment]
Found that it was the dom4-polyfill that was causing this.
When using the classList polyfill before the dom4 polyfill it works fine.
