### ISSUE TITLE
loadMissingEntities issue when bundling with webpack

### ISSUE THREAD

**Issue by hubgit** [mathjax/mathjax-v3#88]
In general `mathjax3` is working nicely with webpack, except for one warning ("the request of a dependency is an expression") due to the dynamic importing of missing MathML entities:

https://github.com/mathjax/mathjax-v3/blob/83174b9af8f142f5b3f43908fcc70f297d8f2159/mathjax3-ts/input/mathml/MmlEntities.ts#L542

which ends up being `System.import('mathjax/input/mathml/js/entities/' + file + '.js')`

One issue here is the warning, the other is that the import path seems incorrect - it should perhaps be `'mathjax3/mathjax3/input/mathml/entities/' + file + '.js'`.

However, given that webpack is going to bundle _everything_ in the `entities` folder so that the dynamic import can always be satisfied, would it make sense to generate a single file containing all the entities and import that statically?

**Comment by dpvc** [comment]
> would it make sense to generate a single file containing all the entities and import that statically?

There already is such a file:  `mathjax3/input/mathml/AllEntities.js`.  If you import that into your script, it will pre-load all the entities.

You are right that the file path is incorrect (there was a restructuring that wasn't reflected here).  That should be fixed.

The `asynchLoad()` code needs to be revisited.  It was needed initially during the period when we still had version 2 code hooked in as we were rewriting the various modules, but it may be eliminated in the end.  In any case, I have been thinking about making it be conditionally compiled so that it does not cause web pack warnings.

**Comment by hubgit** [comment]
Thanks, `mathjax3/input/mathml/AllEntities.js` looks useful in theory, although I think the imports  might need to be changed to be relative (i.e. `import './entities/a.js';` instead of `import 'entities/a.js';`)?

> In any case, I have been thinking about making it be conditionally compiled so that it does not cause webpack warnings.

Anything that gets rid of the warnings sounds good to me :)

**Comment by dpvc** [comment]
I think you are right.  I thought the file had been used before, but clearly it was never properly tested.  Sigh.  Thanks for the catch.

**Comment by dpvc** [comment]
A fix for the entity importing (#92) has been merged into the master and alpha branches, as well as updates to the `asyncLoad()` function to make it work from any directory, and to provide a disabled version for use with webpack to avoid the warning messages.  For that, you need to add

```
        new webpack.NormalModuleReplacementPlugin(
            /AsyncLoad\.js/,
            function (resource) {
                resource.request = resource.request.replace(/AsyncLoad/,"AsyncLoad-disabled");
            }
        )
```

to the `plugins` array for your webpack configuration.  This will replace the the `asynchLoad()` function with one that always returns failure (and doesn't try to load any files).

**Comment by hubgit** [comment]
This is all good now, thanks @dpvc ⭐️

**Comment by stnor** [comment]
See [this comment](https://github.com/mathjax/mathjax-v3/issues/142#issuecomment-420019355) for a better/safer approach.
